// Taylor Eisman
// ASD 09/12
// Project 1

var json = {
	"recipe1": {
        "recipeName": ["Recipe Name:", "Bacon Wraps"],
		"category": ["Category:", "Appetizers"],
		"ingredient1": ["Ingrediant:", "Cocktail sausages"],
		"measurement1": ["1", "package"],
        "ingredient2": ["Ingrediant", "Bacon"],
        "measurement2": ["1", "pound"],
        "ingrediant3": ["Ingrediant", "Brown sugar"],
        "measurement3": ["1", "Cups"],
        "addToFav": ["Favorite:", "No"],
        "prepTime": ["15", "Minutes"],
        "dateAdded": ["Date Added:", "08/28/2012"],
        "instructions": ["Instructions:", "Cut slab of bacon into quarters. Wrap one piece of quartered bacon slice around each sausage weenie. Place on foil lined cookie sheet. Sprinkle brown sugar on top of each wrapped sausage. Bake at 400 degrees for 30-40 minutes"]
	},
    "recipe2": {
        "recipeName": ["Recipe Name:", "Rock N Roll Crackers"],
        "category": ["Category:", "Appetizers"],
        "ingredient1": ["Ingrediant:", "Ranch salad dressing seasoning mix"],
        "measurement1": ["1", "Package"],
        "ingredient2": ["Ingrediant", "Crushed red pepper"],
        "measurement2": ["1 1/2", "Tablespoon"],
        "ingrediant3": ["Ingrediant", "Garlic powder"],
        "measurement3": ["1", "Teaspoon"],
        "ingrediant4": ["Ingrediant", "Saltine crackers"],
        "measurement4": ["1", "Package"],
        "ingrediant5": ["Ingrediant", "Canola oil"],
        "measurement5": ["1 1/2", "Cups"],
        "addToFav": ["Favorite:", "No"],
        "prepTime": ["20", "Minutes"],
        "dateAdded": ["Date Added:", "08/28/2012"],
        "instructions": ["Instructions:", "In a small bowl mix together salad seasoning mix, red pepper flakes, and garlic powder. Set aside. Place crackers in a large gallon sized sealable container, drizzle with canola oil. Add dry ingredients and seal container. Gently roll container to coat crackers with seasonings. Gently roll crackers every 30 minutes for 4 hours for best results."]
    },
    "recipe3": {
        "recipeName": ["Recipe Name:", "Sausage Cheese Balls"],
        "category": ["Category:", "Appetizers"],
        "ingredient1": ["Ingrediant:", "Pan sausage"],
        "measurement1": ["1", "Pound"],
        "ingredient2": ["Ingrediant", "Bisquick"],
        "measurement2": ["2", "Cups"],
        "ingrediant3": ["Ingrediant", "Grated cheddar cheese"],
        "measurement3": ["8", "Ounces"],
        "addToFav": ["Favorite:", "Yes"],
        "prepTime": ["15", "Minutes"],
        "dateAdded": ["Date Added:", "08/28/2012"],
        "instructions": ["Instructions:", "Mix all ingredients well and form into walnut sized balls. Place on cookie sheet sprayed with Pam or non stick spray. Bake at 370 degrees for 15-20 minutes depending on the size of balls. Can be frozen and heated before serving."]
    },
    "recipe4": {
        "recipeName": ["Recipe Name:", "Popeye's Biscuits"],
        "category": ["Category:", "Breads"],
        "ingredient1": ["Ingrediant:", "Bisquick"],
        "measurement1": ["4", "Cups"],
        "ingredient2": ["Ingrediant", "7-Up"],
        "measurement2": ["3/4", "Cups"],
        "ingrediant3": ["Ingrediant", "Sour cream"],
        "measurement3": ["8", "Ounces"],
        "ingrediant4": ["Ingrediant", "Butter stick"],
        "measurement4": ["1", "Stick"],
        "addToFav": ["Favorite:", "Yes"],
        "prepTime": ["5", "Minutes"],
        "dateAdded": ["Date Added:", "08/28/2012"],
        "instructions": ["Instructions:", "Combine bisquick, 7-up, and sour cream. Stir until lumps are gone. Cut stick of butter in half. Melt 1/2 stick of butter in 9x13 or 9x9 pan. Drop biscuits by tablespoon into pan. Bake at 350 degrees for 10-12 minutes or until brown. Melt remainder of butter and baste the tops of each biscuit. Let stand for about 15 minutes and then serve."]
    },
    "recipe5": {
        "recipeName": ["Recipe Name:", "Bull's-eyes"],
        "category": ["Category:", "Breakfast"],
        "ingredient1": ["Ingrediant:", "Bread"],
        "measurement1": ["1", "Slice"],
        "ingredient2": ["Ingrediant", "Egg"],
        "measurement2": ["1", "Number of Ingrediant"],
        "ingrediant3": ["Ingrediant", "Butter"],
        "measurement3": ["1", "Teaspoon"],
        "ingrediant4": ["Ingrediant", "Salt"],
        "measurement4": ["1", "Pinch"],
        "ingrediant5": ["Ingrediant", "Pepper"],
        "measurement5": ["1", "Pinch"],
        "addToFav": ["Favorite:", "Yes"],
        "prepTime": ["5", "Minutes"],
        "dateAdded": ["Date Added:", "08/28/2012"],
        "instructions": ["Instructions:", "Use the opening of a small glass or jar to cut the center out of a slice of bread. Keep the cut out center. Butter a skillet or pan. Using medium heat on the stove place the circle cut out and the bread slice onto the buttered pan. Crack the egg in the center of the bread, season with salt and pepper. Flip till egg is cooked and cut out toasted. Cut out is great for soaking up the runny yolk if not cooked through out."]
    },
    "recipe6": {
        "recipeName": ["Recipe Name:", "Bull's-eyes"],
        "category": ["Category:", "Breakfast"],
        "ingredient1": ["Ingrediant:", "Bread"],
        "measurement1": ["1", "Slice"],
        "ingredient2": ["Ingrediant", "Egg"],
        "measurement2": ["1", "Number of Ingrediant"],
        "ingrediant3": ["Ingrediant", "Butter"],
        "measurement3": ["1", "Teaspoon"],
        "ingrediant4": ["Ingrediant", "Salt"],
        "measurement4": ["1", "Pinch"],
        "ingrediant5": ["Ingrediant", "Pepper"],
        "measurement5": ["1", "Pinch"],
        "addToFav": ["Favorite:", "Yes"],
        "prepTime": ["5", "Minutes"],
        "dateAdded": ["Date Added:", "08/28/2012"],
        "instructions": ["Instructions:", "Use the opening of a small glass or jar to cut the center out of a slice of bread. Keep the cut out center. Butter a skillet or pan. Using medium heat on the stove place the circle cut out and the bread slice onto the buttered pan. Crack the egg in the center of the bread, season with salt and pepper. Flip till egg is cooked and cut out toasted. Cut out is great for soaking up the runny yolk if not cooked through out."]
    },
}